# Generated by Django 5.0.3 on 2024-06-20 14:13

import datetime
import django.core.validators
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('certification_date', models.DateField()),
                ('certification_time', models.TimeField(default=datetime.time(0, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('dlr', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('level', models.CharField(blank=True, max_length=250, null=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '6. Запись на сертификацию',
                'verbose_name_plural': '6. Запись на сертификацию',
                'ordering': ['job_title', 'certification_date', 'certification_time'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('chapter', models.CharField(max_length=250)),
                ('section', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('content_type', models.CharField(max_length=250)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('slug', models.SlugField(max_length=255)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '5. Контенкт',
                'verbose_name_plural': '5. Контент',
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '7. Список дилеров',
                'verbose_name_plural': '7. Список дилеров',
            },
        ),
        migrations.CreateModel(
            name='Edu_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '8. Список всех программ обучения',
                'verbose_name_plural': '8. Список всех программ обучения',
            },
        ),
        migrations.CreateModel(
            name='Edu_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': '9. Результаты изучения',
                'verbose_name_plural': '9. Результаты изучения',
            },
        ),
        migrations.CreateModel(
            name='Job_titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '6. Список должностей',
                'verbose_name_plural': '6. Список должностей',
            },
        ),
        migrations.CreateModel(
            name='Rights_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_title', models.CharField(max_length=250)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '9. Права доступа',
                'verbose_name_plural': '9. Права доступа',
            },
        ),
        migrations.CreateModel(
            name='Site_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(max_length=100, verbose_name='Название кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/myapp/image/')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '1. Разделы сайта',
                'verbose_name_plural': '1. Разделы сайта',
            },
        ),
        migrations.CreateModel(
            name='Training_chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('chapter', models.CharField(max_length=250)),
                ('section', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('content_type', models.CharField(max_length=250)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '4. Разделы глав обучения',
                'verbose_name_plural': '4. Разделы глав обучения',
            },
        ),
        migrations.CreateModel(
            name='Training_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=250)),
                ('training_id', models.CharField(blank=True, max_length=250)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dlr', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': '6. лист участников тренинга',
                'verbose_name_plural': '6. лист участников тренинга',
                'ordering': ['training_name', 'training_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Training_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '3. Главы программы обучения',
                'verbose_name_plural': '3. Главы программы обучения',
            },
        ),
        migrations.CreateModel(
            name='Training_shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.CharField(blank=True, max_length=250)),
                ('training_name', models.CharField(max_length=250)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('actual_num_participants', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField()),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('dlr', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('is_available', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '6. Запись на тренинги',
                'verbose_name_plural': '6. Запись на тренинги',
                'ordering': ['training_name', 'training_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('file', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Technicians_cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_programs_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.job_titles')),
            ],
            options={
                'verbose_name': '2. Программы обучения',
                'verbose_name_plural': '2. Программы обучения',
            },
        ),
    ]
