# Generated by Django 5.0.3 on 2024-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chaper', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
