# Generated by Django 5.0.3 on 2024-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians_cources',
            name='job_title',
            field=models.CharField(max_length=250),
        ),
    ]
