# Generated by Django 5.0.3 on 2024-04-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_course_structures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/myapp/image/')),
            ],
        ),
    ]
