# Generated by Django 5.0.3 on 2024-06-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_technicians_cources_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians_cources',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.job_titles'),
        ),
    ]
