# Generated by Django 5.0.3 on 2024-06-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_technicians_cources_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicians_cources',
            old_name='job_title',
            new_name='edu_area',
        ),
    ]
