# Generated by Django 5.0.3 on 2024-06-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_job_title_technicians_cources_edu_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians_cources',
            name='edu_area',
            field=models.CharField(max_length=250),
        ),
    ]
