# Generated by Django 5.0.3 on 2024-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
