# Generated by Django 5.0.3 on 2024-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians_cources',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='technicians_cources',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
