# Generated by Django 5.0.3 on 2024-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_technicians_cources_edu_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicians_cources',
            options={'verbose_name': '2. Направления обучения', 'verbose_name_plural': '2. Направления обучения'},
        ),
        migrations.AlterModelOptions(
            name='training_parts',
            options={'verbose_name': '3. Содержание программы обучения', 'verbose_name_plural': '3. Содержание программы обучения'},
        ),
        migrations.RemoveField(
            model_name='training_parts',
            name='area',
        ),
        migrations.AlterField(
            model_name='training_parts',
            name='level',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
