# Generated by Django 5.0.3 on 2024-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_technicians_cources_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians_cources',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
