# Generated by Django 5.0.3 on 2024-06-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_technicians_cources_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training_chapters',
            options={'verbose_name': '4. Содержание конкретной программы обучения', 'verbose_name_plural': '4. Содержание конкретной программы обучения'},
        ),
        migrations.RenameField(
            model_name='training_parts',
            old_name='title',
            new_name='program_name',
        ),
    ]
