# Generated by Django 5.0.3 on 2024-06-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians_cources',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.job_titles'),
        ),
    ]
