# Generated by Django 5.0.3 on 2024-06-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_training_chapters_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_parts',
            old_name='level',
            new_name='edu_programs_name',
        ),
    ]
