# Generated by Django 5.0.3 on 2024-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_technicians_cources_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicians_cources',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
