# Generated by Django 5.0.3 on 2024-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_technicians_cources_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('chaper', models.CharField(max_length=250)),
                ('section', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Course_structures',
        ),
    ]
