# Generated by Django 5.0.3 on 2024-06-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_level_training_parts_edu_programs_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicians_cources',
            old_name='edu_programs_name',
            new_name='edu_area_name',
        ),
    ]
