# Generated by Django 5.0.3 on 2024-06-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_edu_programs_name_technicians_cources_edu_area_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicians_cources',
            old_name='edu_area',
            new_name='area',
        ),
    ]
