# Generated by Django 5.0.3 on 2024-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_training_chapters_delete_course_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians_cources',
            name='is_puplished',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='technicians_cources',
            name='job_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
