# Generated by Django 5.0.3 on 2024-06-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_edu_area_technicians_cources_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_chapters',
            name='area',
        ),
        migrations.RemoveField(
            model_name='training_chapters',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='training_chapters',
            name='level',
        ),
        migrations.RemoveField(
            model_name='training_chapters',
            name='section',
        ),
        migrations.RemoveField(
            model_name='training_chapters',
            name='video',
        ),
    ]
