# Generated by Django 5.0.3 on 2024-05-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_technicians_cources_is_puplished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicians_cources',
            old_name='is_puplished',
            new_name='is_published',
        ),
    ]
