# Generated by Django 5.0.3 on 2024-06-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_training_chapters_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_chapters',
            old_name='chapter',
            new_name='chapter_name',
        ),
        migrations.RenameField(
            model_name='training_chapters',
            old_name='title',
            new_name='program_name',
        ),
    ]
