# Generated by Django 5.0.3 on 2024-05-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_is_puplished_technicians_cources_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('chapter', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='training_chapters',
            old_name='chaper',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='training_chapters',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
    ]
