# Generated by Django 5.0.3 on 2024-06-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_chapter_training_chapters_chapter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_chapters',
            name='image',
        ),
    ]
