# Generated by Django 5.0.3 on 2024-05-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_training_parts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_parts',
            name='chapter',
        ),
    ]
