# Generated by Django 5.0.3 on 2024-06-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_training_chapters_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='area',
            new_name='content_name',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='level',
        ),
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
    ]
