# Generated by Django 5.0.3 on 2024-05-23 11:32

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_training_parts_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_chapters',
            name='content_type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_chapters',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
