# Generated by Django 5.0.3 on 2024-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_training_chapters_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_sections',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='site_sections',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
