# Generated by Django 5.0.3 on 2024-06-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_area_content_content_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_name',
            new_name='chapter_name',
        ),
    ]
