# Generated by Django 5.0.3 on 2024-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_site_sections_is_published_site_sections_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('certification_date', models.DateField()),
                ('certification_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=0)),
                ('dlr', models.CharField(max_length=250)),
                ('employee_id', models.CharField(max_length=250)),
                ('employee_name', models.CharField(max_length=250)),
                ('employee_last_name', models.CharField(max_length=250)),
            ],
        ),
    ]
