# Generated by Django 5.0.3 on 2024-06-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_content_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_parts',
            old_name='edu_programs_name',
            new_name='edu_area_name',
        ),
    ]
