# Generated by Django 5.0.3 on 2024-05-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_certification_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification_appointment',
            name='slug',
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='dlr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='employee_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='employee_last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='employee_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
