# Generated by Django 5.0.3 on 2024-07-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_edu_programs_name_training_parts_edu_area_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training_shedule',
            options={'ordering': ['training_name', 'training_start_date'], 'verbose_name': '8. Список тренингов', 'verbose_name_plural': '8. Список тренингов'},
        ),
    ]
