# Generated by Django 5.0.3 on 2024-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_certification_appointment_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification_appointment',
            name='is_available',
            field=models.BooleanField(default=1),
        ),
    ]
