# Generated by Django 5.0.3 on 2024-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_certification_appointment_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification_appointment',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
