# Generated by Django 5.0.3 on 2024-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cert_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('slug', models.SlugField(max_length=255)),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '11. Новости и инфо',
                'verbose_name_plural': '11. Новости и инфо',
            },
        ),
        migrations.AlterModelOptions(
            name='certification_appointment',
            options={'ordering': ['job_title', 'certification_date', 'certification_time'], 'verbose_name': '06. Запись на сертификацию', 'verbose_name_plural': '06. Запись на сертификацию'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '05. Контенкт', 'verbose_name_plural': '05. Контент'},
        ),
        migrations.AlterModelOptions(
            name='dealers',
            options={'verbose_name': '07. Список дилеров', 'verbose_name_plural': '07. Список дилеров'},
        ),
        migrations.AlterModelOptions(
            name='edu_programs',
            options={'verbose_name': '08. Список всех программ обучения', 'verbose_name_plural': '08. Список всех программ обучения'},
        ),
        migrations.AlterModelOptions(
            name='edu_results',
            options={'verbose_name': '09. Результаты изучения', 'verbose_name_plural': '09. Результаты изучения'},
        ),
        migrations.AlterModelOptions(
            name='job_titles',
            options={'verbose_name': '06. Список должностей', 'verbose_name_plural': '06. Список должностей'},
        ),
        migrations.AlterModelOptions(
            name='rights_access',
            options={'verbose_name': '09. Права доступа', 'verbose_name_plural': '09. Права доступа'},
        ),
        migrations.AlterModelOptions(
            name='site_sections',
            options={'verbose_name': '01. Разделы сайта', 'verbose_name_plural': '01. Разделы сайта'},
        ),
        migrations.AlterModelOptions(
            name='technicians_cources',
            options={'verbose_name': '02. Направления обучения', 'verbose_name_plural': '02. Направления обучения'},
        ),
        migrations.AlterModelOptions(
            name='training_chapters',
            options={'verbose_name': '04. Содержание конкретной программы обучения', 'verbose_name_plural': '04. Содержание конкретной программы обучения'},
        ),
        migrations.AlterModelOptions(
            name='training_participants',
            options={'ordering': ['training_name', 'training_start_date'], 'verbose_name': '06. лист участников тренинга', 'verbose_name_plural': '06. лист участников тренинга'},
        ),
        migrations.AlterModelOptions(
            name='training_parts',
            options={'verbose_name': '03. Содержание программы обучения', 'verbose_name_plural': '03. Содержание программы обучения'},
        ),
        migrations.AlterModelOptions(
            name='training_shedule',
            options={'ordering': ['training_name', 'training_start_date'], 'verbose_name': '08. Список тренингов', 'verbose_name_plural': '08. Список тренингов'},
        ),
    ]
