# Generated by Django 5.0.3 on 2024-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_info_alter_certification_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.TextField(),
        ),
    ]
