# Generated by Django 5.0.3 on 2024-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_certification_appointment_time_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='certification_appointment',
            options={'ordering': ['job_title', 'certification_date', 'certification_time']},
        ),
    ]
