# Generated by Django 5.0.3 on 2024-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_job_titles_alter_certification_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_titles',
            name='is_published',
            field=models.BooleanField(default=1),
        ),
    ]
