# Generated by Django 5.0.3 on 2024-05-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_certification_appointment_dlr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification_appointment',
            name='level',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
