# Generated by Django 5.0.3 on 2024-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_edu_results_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu_programs',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
    ]
