# Generated by Django 5.0.3 on 2024-11-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_edu_programs_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu_programs',
            name='is_available',
        ),
    ]
