# Generated by Django 5.0.3 on 2024-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_certification_appointment_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('is_published', models.BooleanField(default=1)),
            ],
        ),
    ]
