# Generated by Django 5.0.3 on 2024-05-30 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_edu_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainin_name', models.CharField(max_length=250)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('max_participants', models.IntegerField()),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('dlr', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '6. Запись на тренинги',
                'verbose_name_plural': '6. Запись на тренинги',
                'ordering': ['trainin_name', 'training_start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='certification_appointment',
            options={'ordering': ['job_title', 'certification_date', 'certification_time'], 'verbose_name': '5. Запись на сертификацию', 'verbose_name_plural': '5. Запись на сертификацию'},
        ),
        migrations.AlterModelOptions(
            name='dealers',
            options={'verbose_name': '7. Список дилеров', 'verbose_name_plural': '7. Список дилеров'},
        ),
        migrations.AlterModelOptions(
            name='edu_programs',
            options={'verbose_name': '8. Список всех программ обучения', 'verbose_name_plural': '8. Список всех программ обучения'},
        ),
        migrations.AlterModelOptions(
            name='job_titles',
            options={'verbose_name': '6. Список должностей', 'verbose_name_plural': '6. Список должностей'},
        ),
        migrations.AlterModelOptions(
            name='site_sections',
            options={'verbose_name': '1. Разделы сайта', 'verbose_name_plural': '1. Разделы сайта'},
        ),
        migrations.AlterModelOptions(
            name='technicians_cources',
            options={'verbose_name': '2. Программы обучения', 'verbose_name_plural': '2. Программы обучения'},
        ),
        migrations.AlterModelOptions(
            name='training_chapters',
            options={'verbose_name': '4. Разделы глав обучения', 'verbose_name_plural': '4. Разделы глав обучения'},
        ),
        migrations.AlterModelOptions(
            name='training_parts',
            options={'verbose_name': '3. Главы программы обучения', 'verbose_name_plural': '3. Главы программы обучения'},
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='certification_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='certification_appointment',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='edu_programs',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='job_titles',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='site_sections',
            name='button_name',
            field=models.CharField(max_length=100, verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='site_sections',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='site_sections',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='site_sections',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='site_sections',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='technicians_cources',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='training_chapters',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='training_parts',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
    ]
