# Generated by Django 5.0.3 on 2024-05-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_training_shedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training_shedule',
            options={'ordering': ['training_name', 'training_start_date'], 'verbose_name': '6. Запись на тренинги', 'verbose_name_plural': '6. Запись на тренинги'},
        ),
        migrations.RenameField(
            model_name='training_shedule',
            old_name='trainin_name',
            new_name='training_name',
        ),
        migrations.RemoveField(
            model_name='training_shedule',
            name='dlr',
        ),
        migrations.RemoveField(
            model_name='training_shedule',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='training_shedule',
            name='employee_last_name',
        ),
        migrations.RemoveField(
            model_name='training_shedule',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='training_shedule',
            name='time_update',
        ),
    ]
