# Generated by Django 5.0.3 on 2024-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_training_shedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_shedule',
            name='actual_num_participants',
            field=models.IntegerField(default=0),
        ),
    ]
