# Generated by Django 5.0.3 on 2024-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_training_shedule_actual_num_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=250)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dlr', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': '6. лист участников тренинга',
                'verbose_name_plural': '6. лист участников тренинга',
                'ordering': ['training_name', 'training_start_date'],
            },
        ),
    ]
