# Generated by Django 5.0.3 on 2024-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_training_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_shedule',
            name='dlr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='training_shedule',
            name='employee_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='training_shedule',
            name='employee_last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='training_shedule',
            name='employee_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
