# Generated by Django 5.0.3 on 2024-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_training_shedule_training_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_participants',
            name='training_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
